version: "3.3"

services:
  hub:
    image: quay.io/blockstack/gaia-hub:feature.docker-compose
    volumes:
      - "./hub-config:/src/hub/etc"
      - "${LOCAL_DISK}:${GAIA_DISK_STORAGE_ROOT_DIR}"
    ports:
      - "3000:3000"
    environment:
      CONFIG_PATH: "/src/hub/etc/config.json"
      GAIA_DISK_STORAGE_ROOT_DIR: ${GAIA_DISK_STORAGE_ROOT_DIR}
    networks:
      - gaia

  admin:
    image: quay.io/blockstack/gaia-admin:feature.docker-compose
    volumes:
      - "./admin-config:/src/admin/etc"
      - "${LOCAL_DISK}:${GAIA_DISK_STORAGE_ROOT_DIR}"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8009:8009"
    links:
      - hub
    environment:
      CONFIG_PATH: "/src/admin/etc/config.json"
    networks:
      - gaia

  reader:
    image: quay.io/blockstack/gaia-reader:feature.docker-compose
    volumes:
      - "./reader-config:/src/reader/etc"
      - "${LOCAL_DISK}:${GAIA_DISK_STORAGE_ROOT_DIR}"
    ports:
      - "8008:8008"
    links:
      - hub
    environment:
      CONFIG_PATH: "/src/reader/etc/config.json"
      GAIA_DISK_STORAGE_ROOT_DIR: "${GAIA_DISK_STORAGE_ROOT_DIR}"
    networks:
      - gaia

  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    links:
      - hub
      - admin
      - reader
    networks:
      - gaia
    depends_on:
      - hub

networks:
  gaia:
    driver: bridge
