version: "3.3"

services:
  hub:
    image: quay.io/blockstack/gaia-hub:develop
    volumes:
      - "./hub-config:/src/hub/etc"
      - "${GAIA_DISK_STORAGE_ROOT_DIR}:${LOCAL_DISK}"
    ports:
      - "3000:3000"
    environment:
      CONFIG_PATH: "/src/hub/etc/config.json"
      GAIA_DISK_STORAGE_ROOT_DIR: /tmp/gaia-storage
    networks:
      - gaia

  admin:
    image: quay.io/blockstack/gaia-hub:admin
    volumes:
      - "./admin-config:/src/admin/etc"
      - "./hub-config:/tmp/hub"
    ports:
      - "8009:8009"
    environment:
      CONFIG_PATH: "/src/admin/etc/config.json"
    networks:
      - gaia

  reader:
    image: quay.io/blockstack/gaia-hub:reader
    volumes:
      - "./reader-config:/src/reader/etc"
      - "${GAIA_DISK_STORAGE_ROOT_DIR}:${LOCAL_DISK}"
    ports:
      - "8008:8008"
    environment:
      CONFIG_PATH: "/src/reader/etc/config.json"
      GAIA_DISK_STORAGE_ROOT_DIR: "/tmp/gaia-storage"
    networks:
      - gaia

  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - gaia
    depends_on:
      - hub

networks:
  gaia:
    driver: bridge
