version: "3.3"

services:
  hub:
    image: gaia-hub:latest
    volumes:
      - "./config.json:/src/hub/config.json:ro"
    ports:
      - "3000:3000"
    environment:
      CONFIG_PATH: "/src/hub/config.json"
    networks:
      - gaia

  admin:
    image: gaia-hub:admin
    volumes:
      - "./admin.json:/src/admin/config.json:ro"
    ports:
      - "8009:8009"
    environment:
      CONFIG_PATH: "/src/admin/config.json"
    networks:
      - gaia

  reader:
    image: gaia-hub:reader
    volumes:
      - "./reader.json:/src/reader/config.json:ro"
    ports:
      - "8008:8008"
    environment:
      CONFIG_PATH: "/src/reader/config.json"
    networks:
      - gaia

  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - gaia

