version: "3.3"

services:
  hub:
    image: quay.io/blockstack/gaia-hub:feature.docker-compose
    # restart: unless-stopped
    volumes:
      - "./hub-config:/src/hub/etc"
      - "${LOCAL_DISK}:${GAIA_DISK_STORAGE_ROOT_DIR}"
    ports:
      - "3000:3000"
    environment:
      CONFIG_PATH: "/src/hub/etc/config.json"
      GAIA_DISK_STORAGE_ROOT_DIR: ${GAIA_DISK_STORAGE_ROOT_DIR}
    networks:
      - gaia

  admin:
    image: quay.io/blockstack/gaia-admin:feature.docker-compose
    # restart: unless-stopped ## this is handled by systemd in a VM
    volumes:
      - "./admin-config:/src/admin/etc"
      - "./hub-config:/tmp/hub-config"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8009:8009"
    links:
      - hub
    environment:
      CONFIG_PATH: "/src/admin/etc/config.json"
    networks:
      - gaia

  reader:
    image: quay.io/blockstack/gaia-reader:feature.docker-compose
    # restart: unless-stopped ## this is handled by systemd in a VM
    volumes:
      - "./reader-config:/src/reader/etc:ro"
      - "${LOCAL_DISK}:${GAIA_DISK_STORAGE_ROOT_DIR}"
    ports:
      - "8008:8008"
    links:
      - hub
    environment:
      CONFIG_PATH: "/src/reader/etc/config.json"
      GAIA_DISK_STORAGE_ROOT_DIR: "${GAIA_DISK_STORAGE_ROOT_DIR}"
    networks:
      - gaia

  nginx:
    image: nginx:alpine
    # restart: unless-stopped ## this is handled by systemd in a VM
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.template"
      - "./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem"
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/usr/share/nginx/html/certbot"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HTTP_PORT=80
      - SERVER_HTTPS_PORT=443
    links:
      - hub
      - admin
      - reader
    networks:
      - gaia
    depends_on:
      - hub
    # command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
    command: /bin/sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
  certbot:
    image: certbot/certbot:latest
    # restart: unless-stopped ## this is handled by systemd in a VM
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/usr/share/nginx/html/certbot"
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    networks:
      - gaia
    depends_on:
      - nginx
networks:
  gaia:
    driver: bridge
