version: "3.3"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx-ssl.conf:/etc/nginx/conf.d/default.template"
      - "./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem"
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/usr/share/nginx/html/certbot"
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: "${DOMAIN}"
      SERVER_HTTP_PORT: "80"
      SERVER_HTTPS_PORT: "443"
    links:
      - hub
      - admin
      - reader
    networks:
      - gaia
    depends_on:
      - hub
    command: /bin/sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
  certbot:
    image: certbot/certbot:latest
    restart: always
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/usr/share/nginx/html/certbot"
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    networks:
      - gaia
    depends_on:
      - nginx
networks:
  gaia:
    driver: bridge
