name: Containers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        paths:
          - node_modules
          - hub/node_modules
          - reader/node_modules
          - admin/node_modules
        with:
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "hub/package-lock.json" }}-{{ checksum "reader/package-lock.json" }}-{{ checksum "admin/package-lock.json" }}

      - name: npm install
        run: npm install

      - run: mkdir $HOME/.config

      # run tests!
      - run: npm run test

      - run: npm run codecovUpload
