name: Containers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          mkdir ~/.npm
          npm config set prefix '~/.npm'
          export PATH=~/.npm/bin:$PATH
          npm --version
          node --version
          npm install
# Testing tests individually
      - run: npm test --prefix hub
      - run: npm run codecovUpload
